/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
              "surface-container-highest": "#d7e2ff",
              "secondary-fixed": "#dae4ef",
              "tertiary": "#71557c",
              "secondary": "#566069",
              "on-error": "#fff7f7",
              "outline": "#6e7b97",
              "on-primary": "#fff7f8",
              "on-tertiary-container": "#5f446a",
              "outline-variant": "#a5b2d0",
              "on-error-container": "#6e0523",
              "tertiary-container": "#f5d1ff",
              "primary": "#6c5a61",
              "tertiary-fixed": "#f5d1ff",
              "on-secondary": "#f5f9ff",
              "on-secondary-fixed-variant": "#535d66",
              "primary-fixed-dim": "#e6ced6",
              "on-secondary-container": "#49535c",
              "on-primary-fixed-variant": "#68575e",
              "primary-container": "#f4dce4",
              "surface-container-low": "#f1f3ff",
              "primary-fixed": "#f4dce4",
              "surface-container": "#e8eeff",
              "primary-dim": "#5f4f55",
              "on-tertiary": "#fff7fc",
              "secondary-dim": "#4a545d",
              "background": "#f9f9ff",
              "tertiary-fixed-dim": "#e6c3f0",
              "error-container": "#f97386",
              "surface-tint": "#6c5a61",
              "on-surface-variant": "#525f7a",
              "inverse-primary": "#fae2ea",
              "error": "#a8364b",
              "on-tertiary-fixed-variant": "#6a4e74",
              "surface-dim": "#cddaf9",
              "on-primary-fixed": "#4b3b41",
              "surface-variant": "#d7e2ff",
              "on-secondary-fixed": "#374049",
              "on-background": "#25324b",
              "inverse-on-surface": "#979dac",
              "tertiary-dim": "#64496f",
              "surface-bright": "#f9f9ff",
              "on-surface": "#25324b",
              "secondary-fixed-dim": "#cbd6e0",
              "surface": "#f9f9ff",
              "inverse-surface": "#080e1a",
              "on-tertiary-fixed": "#4c3256",
              "on-primary-container": "#5e4d54",
              "surface-container-lowest": "#ffffff",
              "secondary-container": "#dae4ef",
              "surface-container-high": "#dfe8ff",
              "error-dim": "#6b0221"
            },
      fontFamily: {
        sans: ['"Newsreader"', 'serif'],
        serif: ['"Newsreader"', 'serif'],
        display: ['"Newsreader"', 'serif'],
        body: ['"Newsreader"', 'serif'],
        headline: ['"Newsreader"', 'serif'],
        label: ['"Newsreader"', 'serif']
      },
      borderRadius: {
        DEFAULT: "1rem", 
        lg: "2rem", 
        xl: "3rem", 
        full: "9999px"
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'scan': 'scan 2s linear infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'fadeIn': 'fadeIn 0.5s ease-out',
        'slideUp': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      }
    },
  },
  plugins: [],
}
